import enum

class CaseState(str, enum.Enum):
    NEW = "NEW"
    ANALYZING = "ANALYZING"
    TRACING = "TRACING"
    PATTERN_ANALYSIS = "PATTERN_ANALYSIS"
    RISK_ANALYSIS = "RISK_ANALYSIS"
    ATTRIBUTION = "ATTRIBUTION"
    EVIDENCE_COLLECTION = "EVIDENCE_COLLECTION"
    REPORT_GENERATION = "REPORT_GENERATION"
    REPORT_READY = "REPORT_READY"
    INVESTIGATOR_REVIEW = "INVESTIGATOR_REVIEW"
    FOLLOW_UP = "FOLLOW_UP"
    CLOSED = "CLOSED"

class StageStatus(str, enum.Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"